name: Daily Portfolio Tracker

on:
  schedule:
    - cron: '20 20 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run tracker
        env:
          ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
        run: python main.py

      - name: Publish artifacts to docs
        run: |
          mkdir -p docs
          cp -f data/portfolio_history.csv docs/portfolio_history.csv
          cp -f reports/latest_report.md docs/latest_report.md
          
      - name: Commit results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update portfolio history [skip ci]" || echo "No changes"
          git push
